# This workflow is run whenever a pull request is opened, re-opened, or taken
# out of draft (ready for review). 
#
# NOTE: pull_request_target behaves the same as pull_request except it grants a
# read/write token to workflows running on a pull request from a fork. While this 
# may seem unsafe, we are limiting the permissions of the Github token below.
name: Assign
on: 
  pull_request_target:
    types: [assigned, opened, reopened, ready_for_review]
# Only grant write permissions to pull requests for the Github token. 
# The default is write permissions to many resources, but it's best 
# practice to keep the scope as small as possible. 
permissions:  
  pull-requests: write
jobs:
  auto-request-review:
    name: Auto Request Review
    runs-on: ubuntu-latest
    steps:
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic.
      - name: Checkout master branch
        uses: actions/checkout@master        
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
      # Run "assign-reviewers" subcommand on bot.
      - name: Assigning reviewers 
        run: cd .github/workflows && go run cmd/main.go --token=${{ secrets.GITHUB_TOKEN }} --reviewers=${{ secrets.reviewers }} assign-reviewers
