# Workflow will trigger on all pull request (except draft), pull request review, and commit push to a 
# pull request (synchronize) event types
# 
# NOTE: pull_request_target behaves the same as pull_request except it gives a
# read/write token to workflows running on a pull request from a fork. While this 
# may seem unsafe, there is a repository rule setting that requires approval from a maintainer 
# to run workflows for external contributors' pull requests. Those who approve workflow runs 
# must be looking through the workflow files attentively and ensuring there aren't any malicious 
# changes. 
name: Check
on: 
  pull_request_review:
    type: [submitted, edited, dismissed]
  pull_request_target: 
    types: [assigned, opened, reopened, ready_for_review, synchronize]

jobs: 
  check-reviews:
    name: Checking reviewers 
    runs-on: ubuntu-latest
    steps:
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic. 
      - name: Checkout master branch 
        uses: actions/checkout@master
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
        # Run "check-reviewers" subcommand on bot.
      - name: Checking reviewers
        run: cd tool/ci && go run cmd/bot.go --token=${{ secrets.GITHUB_TOKEN }} --reviewers=${{ secrets.reviewers }} check-reviewers